import type { ClientNotification } from "@/lib/types/client-settings";

export const SEED_CLIENT_NOTIFICATIONS: ClientNotification[] = [
  { id: "cn1", category: "proposals", priority: "high", status: "unread", title: "New Proposal Received", description: "Marcus Johnson submitted a proposal for E-commerce Platform Redesign — $7,200, 10 weeks.", timestamp: "30 min ago", actionLabel: "Review Proposal", actionHref: "/client/proposals/prop-2", icon: "FileCheck" },
  { id: "cn2", category: "messages", priority: "medium", status: "unread", title: "Freelancer Replied", description: "Sarah Chen sent you a message about the E-commerce Platform Redesign.", timestamp: "1 hour ago", actionLabel: "View Message", actionHref: "/client/messages", icon: "MessageSquare" },
  { id: "cn3", category: "contracts", priority: "high", status: "unread", title: "Milestone Submitted", description: "Sarah Chen submitted Frontend Development milestone for review.", timestamp: "2 hours ago", actionLabel: "Review Work", actionHref: "/client/contracts/cc-001/milestones/cc-001-m2", icon: "Briefcase" },
  { id: "cn4", category: "payments", priority: "medium", status: "read", title: "Payment Released", description: "$2,000 released to Sarah Chen for UI Design milestone.", timestamp: "1 day ago", actionLabel: "View Receipt", actionHref: "/client/escrow/receipts/cr-001", icon: "DollarSign" },
  { id: "cn5", category: "contracts", priority: "medium", status: "read", title: "Contract Completed", description: "Mobile App Landing Page contract with Elena Rodriguez is fully completed.", timestamp: "3 days ago", actionLabel: "View Contract", actionHref: "/client/contracts/cc-003", icon: "CheckCircle" },
  { id: "cn6", category: "projects", priority: "low", status: "read", title: "Project Published", description: "Your Brand Identity Package project is now live on the marketplace.", timestamp: "4 days ago", actionLabel: "View Project", actionHref: "/client/projects/cp-seed-5", icon: "Briefcase" },
  { id: "cn7", category: "proposals", priority: "medium", status: "read", title: "Proposal Shortlisted", description: "You shortlisted Elena Rodriguez for SaaS Dashboard UI.", timestamp: "5 days ago", actionLabel: "View Proposal", actionHref: "/client/proposals/prop-3", icon: "FileCheck" },
  { id: "cn8", category: "payments", priority: "high", status: "unread", title: "Escrow Funded", description: "$3,500 funded in escrow for Brand Identity Package contract.", timestamp: "6 days ago", actionLabel: "View Escrow", actionHref: "/client/escrow", icon: "Wallet" },
  { id: "cn9", category: "messages", priority: "low", status: "read", title: "Freelancer Replied", description: "Elena Rodriguez shared logo concepts for Brand Identity Package.", timestamp: "1 week ago", actionLabel: "View Message", actionHref: "/client/messages", icon: "MessageSquare" },
  { id: "cn10", category: "system", priority: "low", status: "read", title: "Profile Verified", description: "Your company profile has been verified. Verification badge is now active.", timestamp: "2 weeks ago", actionLabel: "View Profile", actionHref: "/client/profile", icon: "Shield" },
];
