import type { ClientProposal, ContractMilestone } from "@/lib/types/client-proposal";

export const CLIENT_PROPOSAL_BUDGET_FILTERS = [
  { value: "under-2k", label: "Under $2,000", min: 0, max: 2000 },
  { value: "2k-5k", label: "$2,000 – $5,000", min: 2000, max: 5000 },
  { value: "5k-10k", label: "$5,000 – $10,000", min: 5000, max: 10000 },
  { value: "10k-plus", label: "$10,000+", min: 10000, max: Infinity },
];

export const SEED_CLIENT_PROPOSALS: ClientProposal[] = [
  {
    id: "prop-1",
    projectId: "cp-seed-1",
    projectTitle: "E-commerce Platform Redesign",
    freelancerId: "sarah-chen",
    freelancerName: "Sarah Chen",
    freelancerAvatar: "SC",
    freelancerTitle: "Senior Frontend Developer",
    rating: 4.9,
    jobSuccessScore: 98,
    experienceLevel: "Expert",
    hourlyRate: 85,
    expectedBudget: "$6,500",
    expectedBudgetAmount: 6500,
    deliveryTime: "8 weeks",
    proposalScore: 96,
    coverLetterPreview:
      "I'd love to help redesign your e-commerce platform. With 6+ years in React and Next.js, I've delivered similar storefront projects that increased conversion by 35%...",
    coverLetter:
      "Hello,\n\nI'd love to help redesign your e-commerce platform. With 6+ years specializing in React and Next.js, I've delivered similar storefront projects for D2C brands that increased conversion rates by 35% and improved mobile performance scores to 98+.\n\nI understand you need a modern, mobile-first experience with seamless checkout. My approach combines a component-driven architecture with performance budgets at every milestone.",
    projectUnderstanding:
      "You need a full storefront redesign with improved UX, faster load times, and Shopify integration while maintaining your premium brand identity.",
    proposedSolution:
      "Phase 1: Discovery & wireframes. Phase 2: Component library in Next.js. Phase 3: Page builds with performance optimization. Phase 4: Shopify integration and QA.",
    timeline: "8 weeks with weekly milestone reviews",
    estimatedCost: "$6,500 (fixed price)",
    portfolioReferences: [
      { id: "pr1", title: "FinTech Dashboard", description: "Real-time analytics dashboard with React" },
      { id: "pr2", title: "E-commerce Storefront", description: "Premium D2C store rebuild" },
    ],
    skillMatches: [
      { skill: "React", percentage: 98 },
      { skill: "Next.js", percentage: 95 },
      { skill: "UI/UX", percentage: 88 },
      { skill: "Communication", percentage: 97 },
    ],
    overallMatch: 96,
    portfolioStrength: 92,
    projectsCompleted: 52,
    responseTime: "< 1 hour",
    availability: "available",
    status: "shortlisted",
    submittedDate: "Jun 3, 2026",
    submittedAt: "2026-06-03T10:00:00Z",
  },
  {
    id: "prop-2",
    projectId: "cp-seed-1",
    projectTitle: "E-commerce Platform Redesign",
    freelancerId: "marcus-johnson",
    freelancerName: "Marcus Johnson",
    freelancerAvatar: "MJ",
    freelancerTitle: "Full Stack Engineer",
    rating: 4.8,
    jobSuccessScore: 96,
    experienceLevel: "Expert",
    hourlyRate: 95,
    expectedBudget: "$7,200",
    expectedBudgetAmount: 7200,
    deliveryTime: "10 weeks",
    proposalScore: 89,
    coverLetterPreview:
      "I can deliver a scalable e-commerce solution with robust backend integration. My experience with payment APIs and high-traffic systems makes me a strong fit...",
    coverLetter:
      "Hi there,\n\nI specialize in full-stack e-commerce builds with Node.js and React. I've architected payment systems processing 1M+ daily requests and can ensure your Shopify integration is rock-solid.",
    projectUnderstanding:
      "A complete platform overhaul requiring frontend excellence and reliable backend/Shopify connectivity with performance targets under 2s mobile load.",
    proposedSolution:
      "Headless commerce architecture with Next.js frontend, API layer for Shopify, and comprehensive monitoring. Includes load testing before launch.",
    timeline: "10 weeks across 4 milestones",
    estimatedCost: "$7,200 (fixed price)",
    portfolioReferences: [
      { id: "pr3", title: "Payment API", description: "Stripe-integrated payment system" },
    ],
    skillMatches: [
      { skill: "React", percentage: 85 },
      { skill: "Next.js", percentage: 80 },
      { skill: "UI/UX", percentage: 72 },
      { skill: "Communication", percentage: 90 },
    ],
    overallMatch: 89,
    portfolioStrength: 85,
    projectsCompleted: 41,
    responseTime: "< 2 hours",
    availability: "available",
    status: "new",
    submittedDate: "Jun 5, 2026",
    submittedAt: "2026-06-05T14:30:00Z",
  },
  {
    id: "prop-3",
    projectId: "cp-seed-2",
    projectTitle: "SaaS Dashboard UI",
    freelancerId: "elena-rodriguez",
    freelancerName: "Elena Rodriguez",
    freelancerAvatar: "ER",
    freelancerTitle: "Product Designer",
    rating: 5.0,
    jobSuccessScore: 100,
    experienceLevel: "Expert",
    hourlyRate: 75,
    expectedBudget: "$3,800",
    expectedBudgetAmount: 3800,
    deliveryTime: "4 weeks",
    proposalScore: 94,
    coverLetterPreview:
      "Your SaaS dashboard project aligns perfectly with my design systems expertise. I'll deliver pixel-perfect Figma designs and React components...",
    coverLetter:
      "Hello,\n\nAs a product designer with 5+ years in SaaS interfaces, I understand the balance between data density and clarity. I'll create a comprehensive design system your dev team can implement efficiently.",
    projectUnderstanding:
      "You need a responsive admin dashboard with analytics widgets, user management, and a cohesive design language for your B2B product.",
    proposedSolution:
      "User research synthesis, wireframes, high-fidelity Figma designs, interactive prototype, and handoff documentation with component specs.",
    timeline: "4 weeks: Research (1w) → Design (2w) → Handoff (1w)",
    estimatedCost: "$3,800 (fixed price)",
    portfolioReferences: [
      { id: "pr4", title: "Brand Identity", description: "Complete fintech brand system" },
      { id: "pr5", title: "Mobile App UI", description: "Fitness app interface design" },
    ],
    skillMatches: [
      { skill: "React", percentage: 70 },
      { skill: "Next.js", percentage: 65 },
      { skill: "UI/UX", percentage: 99 },
      { skill: "Communication", percentage: 96 },
    ],
    overallMatch: 94,
    portfolioStrength: 97,
    projectsCompleted: 35,
    responseTime: "< 3 hours",
    availability: "busy",
    status: "new",
    submittedDate: "Jun 6, 2026",
    submittedAt: "2026-06-06T09:00:00Z",
  },
  {
    id: "prop-4",
    projectId: "cp-seed-2",
    projectTitle: "SaaS Dashboard UI",
    freelancerId: "david-kim",
    freelancerName: "David Kim",
    freelancerAvatar: "DK",
    freelancerTitle: "Frontend Developer",
    rating: 4.7,
    jobSuccessScore: 97,
    experienceLevel: "Expert",
    hourlyRate: 80,
    expectedBudget: "$4,100",
    expectedBudgetAmount: 4100,
    deliveryTime: "5 weeks",
    proposalScore: 87,
    coverLetterPreview:
      "I build production-ready dashboards with React and modern charting libraries. Happy to share similar admin panel work from recent clients...",
    coverLetter:
      "Hi,\n\nI've built 12+ SaaS admin dashboards with React, Recharts, and TanStack Table. I focus on accessible, performant interfaces that scale with your data.",
    projectUnderstanding:
      "A functional admin dashboard with analytics, user management, and responsive layouts for your growing B2B platform.",
    proposedSolution:
      "Component-based dashboard with reusable chart widgets, role-based views, and Storybook documentation for your team.",
    timeline: "5 weeks with bi-weekly demos",
    estimatedCost: "$4,100 (fixed price)",
    portfolioReferences: [
      { id: "pr6", title: "Analytics Dashboard", description: "Real-time metrics platform" },
    ],
    skillMatches: [
      { skill: "React", percentage: 94 },
      { skill: "Next.js", percentage: 88 },
      { skill: "UI/UX", percentage: 82 },
      { skill: "Communication", percentage: 88 },
    ],
    overallMatch: 87,
    portfolioStrength: 88,
    projectsCompleted: 38,
    responseTime: "< 1 hour",
    availability: "available",
    status: "saved",
    submittedDate: "Jun 7, 2026",
    submittedAt: "2026-06-07T11:00:00Z",
  },
  {
    id: "prop-5",
    projectId: "cp-seed-3",
    projectTitle: "Mobile App Landing Page",
    freelancerId: "sarah-chen",
    freelancerName: "Sarah Chen",
    freelancerAvatar: "SC",
    freelancerTitle: "Senior Frontend Developer",
    rating: 4.9,
    jobSuccessScore: 98,
    experienceLevel: "Expert",
    hourlyRate: 85,
    expectedBudget: "$1,100",
    expectedBudgetAmount: 1100,
    deliveryTime: "1 week",
    proposalScore: 98,
    coverLetterPreview:
      "Landing pages are my specialty. I can deliver a high-converting, animated mobile-first page within your timeline and budget...",
    coverLetter:
      "Hello,\n\nI specialize in high-converting landing pages with Next.js and Framer Motion. I'll deliver a mobile-optimized page with A/B-ready sections and 95+ Lighthouse scores.",
    projectUnderstanding:
      "You need a compelling fitness app launch page with animations, social proof, and mobile optimization for app store conversion.",
    proposedSolution:
      "Hero with motion graphics, feature sections, testimonials, CTA optimization, and analytics event tracking setup.",
    timeline: "5 business days from kickoff",
    estimatedCost: "$1,100 (fixed price)",
    portfolioReferences: [
      { id: "pr7", title: "SaaS Landing Page", description: "Converted at 8.2%" },
    ],
    skillMatches: [
      { skill: "React", percentage: 97 },
      { skill: "Next.js", percentage: 96 },
      { skill: "UI/UX", percentage: 90 },
      { skill: "Communication", percentage: 97 },
    ],
    overallMatch: 98,
    portfolioStrength: 92,
    projectsCompleted: 52,
    responseTime: "< 1 hour",
    availability: "available",
    status: "accepted",
    submittedDate: "May 30, 2026",
    submittedAt: "2026-05-30T08:00:00Z",
  },
  {
    id: "prop-6",
    projectId: "cp-seed-3",
    projectTitle: "Mobile App Landing Page",
    freelancerId: "james-wilson",
    freelancerName: "James Wilson",
    freelancerAvatar: "JW",
    freelancerTitle: "Marketing Specialist",
    rating: 4.6,
    jobSuccessScore: 94,
    experienceLevel: "Intermediate",
    hourlyRate: 55,
    expectedBudget: "$900",
    expectedBudgetAmount: 900,
    deliveryTime: "1 week",
    proposalScore: 78,
    coverLetterPreview:
      "I combine conversion copywriting with clean landing page builds. Let me show you pages I've optimized for 40%+ conversion lifts...",
    coverLetter:
      "Hi,\n\nI build landing pages that convert. My approach pairs persuasive copy with clean design to maximize sign-ups for app launches.",
    projectUnderstanding:
      "A conversion-focused landing page for a fitness app launch targeting mobile users and app store downloads.",
    proposedSolution:
      "Copy-first wireframes, mobile-responsive build, heatmap-ready layout, and post-launch conversion recommendations.",
    timeline: "7 days delivery",
    estimatedCost: "$900 (fixed price)",
    portfolioReferences: [
      { id: "pr8", title: "SaaS Launch Page", description: "12% conversion rate" },
    ],
    skillMatches: [
      { skill: "React", percentage: 60 },
      { skill: "Next.js", percentage: 55 },
      { skill: "UI/UX", percentage: 75 },
      { skill: "Communication", percentage: 92 },
    ],
    overallMatch: 78,
    portfolioStrength: 80,
    projectsCompleted: 28,
    responseTime: "< 4 hours",
    availability: "available",
    status: "rejected",
    submittedDate: "May 29, 2026",
    submittedAt: "2026-05-29T16:00:00Z",
  },
  {
    id: "prop-7",
    projectId: "cp-seed-4",
    projectTitle: "AI Customer Support Chatbot",
    freelancerId: "priya-sharma",
    freelancerName: "Priya Sharma",
    freelancerAvatar: "PS",
    freelancerTitle: "ML Engineer",
    rating: 4.9,
    jobSuccessScore: 99,
    experienceLevel: "Expert",
    hourlyRate: 95,
    expectedBudget: "$5,500",
    expectedBudgetAmount: 5500,
    deliveryTime: "10 weeks",
    proposalScore: 93,
    coverLetterPreview:
      "I've built production chatbots using OpenAI and custom NLP pipelines. Your help desk integration requirements are well within my expertise...",
    coverLetter:
      "Hello,\n\nI specialize in AI chatbots for customer support with OpenAI and custom fine-tuning. I've reduced support ticket volume by 60% for SaaS clients.",
    projectUnderstanding:
      "An AI chatbot integrated with your help desk to automate tier-1 support with escalation paths to human agents.",
    proposedSolution:
      "RAG-based knowledge retrieval, OpenAI integration, help desk webhook setup, analytics dashboard, and 2 weeks post-launch tuning.",
    timeline: "10 weeks across 5 milestones",
    estimatedCost: "$5,500 (hourly, ~58 hours)",
    portfolioReferences: [
      { id: "pr9", title: "Support Bot", description: "60% ticket deflection" },
    ],
    skillMatches: [
      { skill: "React", percentage: 70 },
      { skill: "Next.js", percentage: 65 },
      { skill: "UI/UX", percentage: 68 },
      { skill: "Communication", percentage: 94 },
    ],
    overallMatch: 93,
    portfolioStrength: 90,
    projectsCompleted: 31,
    responseTime: "< 2 hours",
    availability: "available",
    status: "shortlisted",
    submittedDate: "May 22, 2026",
    submittedAt: "2026-05-22T12:00:00Z",
  },
  {
    id: "prop-8",
    projectId: "cp-seed-7",
    projectTitle: "Stripe Payment Integration",
    freelancerId: "marcus-johnson",
    freelancerName: "Marcus Johnson",
    freelancerAvatar: "MJ",
    freelancerTitle: "Full Stack Engineer",
    rating: 4.8,
    jobSuccessScore: 96,
    experienceLevel: "Expert",
    hourlyRate: 95,
    expectedBudget: "$1,600",
    expectedBudgetAmount: 1600,
    deliveryTime: "3 weeks",
    proposalScore: 91,
    coverLetterPreview:
      "Stripe integrations are core to my practice. I've implemented subscriptions, webhooks, and multi-currency support across dozens of projects...",
    coverLetter:
      "Hi,\n\nI've integrated Stripe into 20+ Next.js applications including subscription billing, one-time payments, and webhook-driven fulfillment.",
    projectUnderstanding:
      "Integrate Stripe subscriptions and one-time payments into your Next.js app with robust webhook handling and error recovery.",
    proposedSolution:
      "Stripe Checkout + Customer Portal, webhook handlers with idempotency, test coverage, and deployment documentation.",
    timeline: "3 weeks: Setup (1w) → Integration (1w) → Testing (1w)",
    estimatedCost: "$1,600 (fixed price)",
    portfolioReferences: [
      { id: "pr10", title: "Payment API", description: "Stripe + PayPal dual integration" },
    ],
    skillMatches: [
      { skill: "React", percentage: 82 },
      { skill: "Next.js", percentage: 88 },
      { skill: "UI/UX", percentage: 70 },
      { skill: "Communication", percentage: 90 },
    ],
    overallMatch: 91,
    portfolioStrength: 85,
    projectsCompleted: 41,
    responseTime: "< 2 hours",
    availability: "available",
    status: "new",
    submittedDate: "Jun 9, 2026",
    submittedAt: "2026-06-09T10:00:00Z",
  },
];

export const AI_RECOMMENDED_FREELANCERS = [
  {
    freelancerId: "sarah-chen",
    name: "Sarah Chen",
    avatar: "SC",
    title: "Senior Frontend Developer",
    matchPercentage: 98,
    rating: 4.9,
    portfolioStrength: 92,
    reason: "Best match for React & Next.js projects",
  },
  {
    freelancerId: "elena-rodriguez",
    name: "Elena Rodriguez",
    avatar: "ER",
    title: "Product Designer",
    matchPercentage: 96,
    rating: 5.0,
    portfolioStrength: 97,
    reason: "Top-rated for UI/UX and design systems",
  },
  {
    freelancerId: "priya-sharma",
    name: "Priya Sharma",
    avatar: "PS",
    title: "ML Engineer",
    matchPercentage: 94,
    rating: 4.9,
    portfolioStrength: 90,
    reason: "Expert in AI integrations and chatbots",
  },
];

export function getContractMilestones(proposal: ClientProposal): ContractMilestone[] {
  const total = proposal.expectedBudgetAmount;
  return [
    {
      id: "m1",
      title: "Project Kickoff & Planning",
      amount: `$${Math.round(total * 0.2).toLocaleString()}`,
      dueDate: "Week 1",
    },
    {
      id: "m2",
      title: "Core Deliverables",
      amount: `$${Math.round(total * 0.5).toLocaleString()}`,
      dueDate: "Mid-project",
    },
    {
      id: "m3",
      title: "Final Delivery & QA",
      amount: `$${Math.round(total * 0.3).toLocaleString()}`,
      dueDate: "Completion",
    },
  ];
}
