import type {
  ActiveProject,
  ActivityItem,
  Certification,
  ClientReview,
  DashboardStat,
  FreelancerProfile,
  MonthlyEarning,
  PortfolioItem,
  PortfolioStats,
  ProfileRecommendation,
  RecommendedProject,
  Skill,
} from "@/lib/types/dashboard";

export const freelancerProfile: FreelancerProfile = {
  name: "Sarah Chen",
  avatar: "SC",
  title: "Senior Frontend Developer",
  availability: "available",
  email: "sarah.chen@email.com",
};

export const dashboardStats: DashboardStat[] = [
  {
    id: "earnings",
    label: "Total Earnings",
    value: "$48,250",
    change: 12.5,
    trend: "up",
    icon: "DollarSign",
  },
  {
    id: "active",
    label: "Active Projects",
    value: "3",
    change: 0,
    trend: "neutral",
    icon: "FolderKanban",
  },
  {
    id: "proposals",
    label: "Pending Proposals",
    value: "7",
    change: 16.7,
    trend: "up",
    icon: "Send",
  },
  {
    id: "strength",
    label: "Profile Strength",
    value: "78%",
    change: 5.2,
    trend: "up",
    icon: "Gauge",
  },
  {
    id: "completed",
    label: "Completed Projects",
    value: "24",
    change: 8.3,
    trend: "up",
    icon: "CheckCircle",
  },
  {
    id: "success",
    label: "Success Rate",
    value: "96%",
    change: 2.1,
    trend: "up",
    icon: "TrendingUp",
  },
];

export const monthlyEarnings: MonthlyEarning[] = [
  { month: "Jan", earnings: 6200, projects: 2 },
  { month: "Feb", earnings: 7800, projects: 3 },
  { month: "Mar", earnings: 5400, projects: 2 },
  { month: "Apr", earnings: 9100, projects: 3 },
  { month: "May", earnings: 8500, projects: 2 },
  { month: "Jun", earnings: 11250, projects: 4 },
];

export const proposalConversionData = [
  { name: "Submitted", value: 45, color: "#2563EB" },
  { name: "Viewed", value: 32, color: "#6366F1" },
  { name: "Interviewed", value: 18, color: "#8B5CF6" },
  { name: "Won", value: 12, color: "#22C55E" },
];

export const activeProjects: ActiveProject[] = [
  {
    id: "1",
    name: "E-commerce Platform Redesign",
    client: "Michael Torres",
    progress: 65,
    deadline: "Jul 15, 2026",
    status: "In Progress",
  },
  {
    id: "2",
    name: "SaaS Dashboard UI",
    client: "Jessica Park",
    progress: 40,
    deadline: "Aug 2, 2026",
    status: "In Progress",
  },
  {
    id: "3",
    name: "Mobile App Landing Page",
    client: "David Kim",
    progress: 90,
    deadline: "Jun 20, 2026",
    status: "Review",
  },
  {
    id: "4",
    name: "Design System Documentation",
    client: "Elena Rodriguez",
    progress: 10,
    deadline: "Aug 10, 2026",
    status: "Starting Soon",
  },
];

export const recommendedProjects: RecommendedProject[] = [
  {
    id: "ecommerce-redesign",
    title: "E-commerce Platform Redesign",
    matchPercentage: 98,
    budget: "$5,000 – $8,000",
    skills: ["React", "Next.js", "UI/UX"],
    clientRating: 4.9,
  },
  {
    id: "landing-page",
    title: "SaaS Landing Page Development",
    matchPercentage: 95,
    budget: "$800 – $1,200",
    skills: ["React", "Next.js", "Tailwind"],
    clientRating: 4.5,
  },
  {
    id: "api-integration",
    title: "Stripe & PayPal Payment Integration",
    matchPercentage: 88,
    budget: "$600 – $900",
    skills: ["Node.js", "React"],
    clientRating: 4.6,
  },
  {
    id: "ai-chatbot",
    title: "AI Customer Support Chatbot",
    matchPercentage: 82,
    budget: "$4,000 – $6,000",
    skills: ["AI", "Python", "React"],
    clientRating: 4.8,
  },
  {
    id: "ui-audit",
    title: "UI/UX Audit & Redesign",
    matchPercentage: 91,
    budget: "$300 – $500",
    skills: ["UI/UX", "Figma"],
    clientRating: 4.4,
  },
  {
    id: "mobile-app-mvp",
    title: "Fitness Tracking Mobile App MVP",
    matchPercentage: 79,
    budget: "$10,000 – $15,000",
    skills: ["React", "Node.js"],
    clientRating: 4.7,
  },
];

export const recentActivity: ActivityItem[] = [
  {
    id: "1",
    type: "proposal",
    title: "Proposal Submitted",
    description: "Applied to SaaS Landing Page Development",
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    type: "payment",
    title: "Payment Released",
    description: "$2,500 received for Mobile App Landing Page milestone",
    timestamp: "5 hours ago",
  },
  {
    id: "3",
    type: "accepted",
    title: "Project Accepted",
    description: "Design System Documentation project confirmed by Elena Rodriguez",
    timestamp: "1 day ago",
  },
  {
    id: "4",
    type: "portfolio",
    title: "Portfolio Updated",
    description: "Added FinTech Dashboard project to portfolio",
    timestamp: "2 days ago",
  },
  {
    id: "5",
    type: "review",
    title: "New Review Received",
    description: "5-star review from Michael Torres for E-commerce Redesign",
    timestamp: "3 days ago",
  },
  {
    id: "6",
    type: "proposal",
    title: "Proposal Viewed",
    description: "Client viewed your proposal for AI Chatbot Integration",
    timestamp: "4 days ago",
  },
];

export const profileRecommendations: ProfileRecommendation[] = [
  { id: "portfolio", label: "Add Portfolio", completed: true, href: "/dashboard/portfolio" },
  { id: "skills", label: "Add Skills", completed: true, href: "/dashboard/portfolio#skills" },
  { id: "verify", label: "Verify Identity", completed: false, href: "#" },
  { id: "bio", label: "Complete Bio", completed: false, href: "#" },
];

export const profileStrength = 78;

export const portfolioStats: PortfolioStats = {
  views: 2847,
  likes: 186,
  clientContacts: 42,
  savedByClients: 67,
};

const THUMBNAILS = [
  "from-blue-500 to-indigo-600",
  "from-violet-500 to-purple-600",
  "from-emerald-500 to-teal-600",
  "from-orange-500 to-amber-600",
  "from-rose-500 to-pink-600",
  "from-cyan-500 to-blue-600",
  "from-fuchsia-500 to-violet-600",
  "from-lime-500 to-green-600",
  "from-sky-500 to-blue-600",
  "from-red-500 to-orange-600",
  "from-indigo-500 to-violet-600",
  "from-teal-500 to-emerald-600",
];

export const portfolioItems: PortfolioItem[] = [
  {
    id: "fintech-dashboard",
    title: "FinTech Analytics Dashboard",
    category: "Web Development",
    technologies: ["React", "TypeScript", "D3.js", "Tailwind"],
    description: "Real-time financial analytics dashboard with interactive charts and portfolio tracking.",
    thumbnail: THUMBNAILS[0],
    views: 342,
    likes: 28,
    projectUrl: "https://example.com/fintech",
    overview: "Built a comprehensive analytics dashboard for a fintech startup, enabling users to track investments, analyze market trends, and manage portfolios in real-time.",
    challenges: ["Handling real-time data streams with 10K+ updates per second", "Complex chart rendering performance on mobile devices", "Ensuring WCAG 2.1 AA compliance for financial data"],
    solutions: ["Implemented WebSocket connections with optimistic UI updates", "Used virtual scrolling and canvas-based chart rendering", "Built accessible color palettes and screen reader support"],
    results: ["40% increase in user engagement", "Page load time reduced from 4.2s to 1.1s", "Featured in Product Hunt's daily top 5"],
    gallery: [THUMBNAILS[0], THUMBNAILS[1], THUMBNAILS[2]],
    createdAt: "May 2026",
  },
  {
    id: "ecommerce-storefront",
    title: "Premium E-commerce Storefront",
    category: "Web Development",
    technologies: ["Next.js", "Stripe", "Sanity CMS"],
    description: "High-converting e-commerce experience for a luxury fashion brand with 3D product previews.",
    thumbnail: THUMBNAILS[1],
    views: 289,
    likes: 24,
    overview: "Designed and developed a premium e-commerce platform featuring 3D product visualization, personalized recommendations, and seamless checkout.",
    challenges: ["Integrating 3D product models without impacting performance", "Building a headless CMS workflow for non-technical staff"],
    solutions: ["Lazy-loaded 3D models with Three.js and progressive enhancement", "Custom Sanity CMS schemas with preview mode"],
    results: ["Conversion rate increased by 35%", "Average order value up 22%", "Mobile bounce rate decreased by 18%"],
    gallery: [THUMBNAILS[1], THUMBNAILS[3]],
    createdAt: "April 2026",
  },
  {
    id: "healthcare-app",
    title: "Healthcare Patient Portal",
    category: "Mobile Apps",
    technologies: ["React Native", "Firebase", "Node.js"],
    description: "HIPAA-compliant patient portal for appointment scheduling, telehealth, and medical records.",
    thumbnail: THUMBNAILS[2],
    views: 256,
    likes: 19,
    overview: "Developed a secure patient portal enabling telehealth consultations, appointment management, and encrypted medical record access.",
    challenges: ["HIPAA compliance requirements", "Offline-first architecture for rural patients"],
    solutions: ["End-to-end encryption with audit logging", "Service worker caching with sync queue"],
    results: ["50K+ active users in first 3 months", "99.9% uptime achieved", "Patient satisfaction score of 4.8/5"],
    gallery: [THUMBNAILS[2], THUMBNAILS[4]],
    createdAt: "March 2026",
  },
  {
    id: "design-system",
    title: "Enterprise Design System",
    category: "Design",
    technologies: ["Figma", "Storybook", "React"],
    description: "Scalable design system with 80+ components used across 12 product teams.",
    thumbnail: THUMBNAILS[3],
    views: 412,
    likes: 45,
    overview: "Created a comprehensive design system unifying visual language across a enterprise SaaS platform with 12 product teams.",
    challenges: ["Aligning 12 teams with different design preferences", "Maintaining consistency across web and mobile"],
    solutions: ["Design tokens with automated sync to code", "Weekly design system office hours and contribution guidelines"],
    results: ["Development speed increased 40%", "Design debt reduced by 60%", "Adopted by all 12 product teams"],
    gallery: [THUMBNAILS[3], THUMBNAILS[5]],
    createdAt: "February 2026",
  },
  {
    id: "ai-content-tool",
    title: "AI Content Generation Tool",
    category: "AI",
    technologies: ["Python", "OpenAI", "Next.js"],
    description: "AI-powered content creation platform for marketing teams with brand voice customization.",
    thumbnail: THUMBNAILS[4],
    views: 198,
    likes: 15,
    overview: "Built an AI content platform that generates on-brand marketing copy, social posts, and blog articles.",
    challenges: ["Maintaining brand voice consistency across generated content", "Handling API rate limits at scale"],
    solutions: ["Fine-tuned prompts with brand guidelines injection", "Queue-based processing with intelligent retry logic"],
    results: ["Content creation time reduced by 70%", "500+ marketing teams onboarded", "4.7 average user rating"],
    gallery: [THUMBNAILS[4], THUMBNAILS[6]],
    createdAt: "January 2026",
  },
  {
    id: "saas-marketing",
    title: "SaaS Marketing Website",
    category: "Web Development",
    technologies: ["Next.js", "Framer Motion", "Tailwind"],
    description: "High-performance marketing site with animated product demos and interactive pricing calculator.",
    thumbnail: THUMBNAILS[5],
    views: 367,
    likes: 31,
    overview: "Developed a conversion-optimized marketing website with interactive product demos and dynamic pricing.",
    challenges: ["Achieving 95+ Lighthouse score with heavy animations", "Building interactive pricing without backend"],
    solutions: ["CSS-based animations with reduced motion support", "Client-side pricing engine with local storage persistence"],
    results: ["Lighthouse score: 98 performance", "Demo request conversion up 45%", "Featured on Awwwards"],
    gallery: [THUMBNAILS[5], THUMBNAILS[7]],
    createdAt: "December 2025",
  },
  {
    id: "project-management",
    title: "Project Management App",
    category: "Web Development",
    technologies: ["React", "Redux", "Node.js", "PostgreSQL"],
    description: "Kanban-style project management tool with real-time collaboration and time tracking.",
    thumbnail: THUMBNAILS[6],
    views: 223,
    likes: 18,
    overview: "Full-stack project management application with Kanban boards, Gantt charts, and team collaboration features.",
    challenges: ["Real-time sync across multiple users editing simultaneously", "Complex permission system for enterprise teams"],
    solutions: ["Operational transformation for conflict-free editing", "Role-based access control with granular permissions"],
    results: ["10K+ teams using the platform", "Average task completion time reduced 25%", "Enterprise tier launched successfully"],
    gallery: [THUMBNAILS[6], THUMBNAILS[8]],
    createdAt: "November 2025",
  },
  {
    id: "restaurant-ordering",
    title: "Restaurant Ordering System",
    category: "Mobile Apps",
    technologies: ["React Native", "Stripe", "Firebase"],
    description: "Contactless ordering and payment system for restaurant chains with kitchen display integration.",
    thumbnail: THUMBNAILS[7],
    views: 178,
    likes: 12,
    overview: "Mobile ordering system enabling contactless dining with QR code menus, table ordering, and kitchen integration.",
    challenges: ["Low-latency order routing to kitchen displays", "Multi-location menu management"],
    solutions: ["Edge-deployed order routing with fallback queues", "Centralized menu CMS with location overrides"],
    results: ["Order processing time reduced 50%", "Deployed across 45 restaurant locations", "Customer satisfaction up 30%"],
    gallery: [THUMBNAILS[7], THUMBNAILS[9]],
    createdAt: "October 2025",
  },
  {
    id: "brand-identity-tech",
    title: "Tech Startup Brand Identity",
    category: "Design",
    technologies: ["Figma", "Illustrator", "After Effects"],
    description: "Complete brand identity including logo, guidelines, and motion design for a Series A startup.",
    thumbnail: THUMBNAILS[8],
    views: 445,
    likes: 52,
    overview: "Crafted a complete brand identity for a fintech startup preparing for Series A, including logo, guidelines, and motion assets.",
    challenges: ["Standing out in crowded fintech market", "Creating scalable brand for international expansion"],
    solutions: ["Distinctive geometric logo system with flexible applications", "Modular brand guidelines with regional adaptation rules"],
    results: ["Brand recognition increased 3x post-rebrand", "Successfully used in $15M Series A pitch", "Won regional design award"],
    gallery: [THUMBNAILS[8], THUMBNAILS[10]],
    createdAt: "September 2025",
  },
  {
    id: "blog-platform",
    title: "Developer Blog Platform",
    category: "Writing",
    technologies: ["Next.js", "MDX", "Vercel"],
    description: "Technical blog platform with syntax highlighting, interactive code demos, and SEO optimization.",
    thumbnail: THUMBNAILS[9],
    views: 156,
    likes: 11,
    overview: "Built a developer-focused blog platform with MDX support, live code editors, and advanced SEO features.",
    challenges: ["Rendering interactive code demos securely", "Optimizing SEO for technical content"],
    solutions: ["Sandboxed iframe execution for code demos", "Structured data and automatic sitemap generation"],
    results: ["Organic traffic grew 200% in 6 months", "Average time on page: 4.5 minutes", "100K+ monthly page views"],
    gallery: [THUMBNAILS[9], THUMBNAILS[11]],
    createdAt: "August 2025",
  },
  {
    id: "social-campaign",
    title: "Social Media Campaign Suite",
    category: "Marketing",
    technologies: ["Canva API", "React", "Analytics"],
    description: "Automated social media campaign management with analytics dashboard and A/B testing.",
    thumbnail: THUMBNAILS[10],
    views: 134,
    likes: 9,
    overview: "Campaign management tool for scheduling, A/B testing, and analyzing social media performance across platforms.",
    challenges: ["Multi-platform API rate limiting", "Accurate cross-platform analytics aggregation"],
    solutions: ["Intelligent scheduling with rate limit awareness", "Unified analytics layer with normalized metrics"],
    results: ["Campaign engagement up 55%", "Content scheduling time reduced 80%", "Used by 200+ marketing teams"],
    gallery: [THUMBNAILS[10], THUMBNAILS[0]],
    createdAt: "July 2025",
  },
  {
    id: "ml-dashboard",
    title: "ML Model Monitoring Dashboard",
    category: "AI",
    technologies: ["Python", "React", "TensorFlow", "Grafana"],
    description: "Real-time ML model performance monitoring with drift detection and automated alerting.",
    thumbnail: THUMBNAILS[11],
    views: 267,
    likes: 22,
    overview: "Dashboard for monitoring ML model performance, detecting data drift, and triggering automated retraining pipelines.",
    challenges: ["Visualizing high-dimensional model metrics", "Real-time drift detection at scale"],
    solutions: ["Dimensionality reduction for metric visualization", "Streaming drift detection with configurable thresholds"],
    results: ["Model downtime reduced by 90%", "False positive alerts decreased 60%", "Deployed monitoring for 15 production models"],
    gallery: [THUMBNAILS[11], THUMBNAILS[1]],
    createdAt: "June 2025",
  },
];

export const skills: Skill[] = [
  { id: "1", name: "React", category: "Frontend", proficiency: 95 },
  { id: "2", name: "Next.js", category: "Frontend", proficiency: 90 },
  { id: "3", name: "TypeScript", category: "Frontend", proficiency: 92 },
  { id: "4", name: "UI/UX", category: "Design", proficiency: 85 },
  { id: "5", name: "Node.js", category: "Backend", proficiency: 80 },
  { id: "6", name: "Tailwind CSS", category: "Frontend", proficiency: 94 },
  { id: "7", name: "Figma", category: "Design", proficiency: 88 },
  { id: "8", name: "Python", category: "Backend", proficiency: 72 },
];

export const certifications: Certification[] = [
  {
    id: "1",
    name: "AWS Certified Developer",
    organization: "Amazon Web Services",
    issueDate: "March 2025",
    credentialId: "AWS-DEV-2025-SC7842",
  },
  {
    id: "2",
    name: "Meta Front-End Developer",
    organization: "Meta",
    issueDate: "January 2025",
    credentialId: "META-FE-2025-92847",
  },
  {
    id: "3",
    name: "Google UX Design Certificate",
    organization: "Google",
    issueDate: "September 2024",
    credentialId: "GUX-2024-38472",
  },
];

export const clientReviews: ClientReview[] = [
  {
    id: "1",
    clientName: "Michael Torres",
    rating: 5,
    review: "Sarah delivered an exceptional e-commerce redesign that exceeded our expectations. Her attention to detail and communication throughout the project was outstanding.",
    projectCompleted: "E-commerce Platform Redesign",
    date: "May 2026",
  },
  {
    id: "2",
    clientName: "Jessica Park",
    rating: 5,
    review: "Working with Sarah on our SaaS dashboard was a pleasure. She understood our vision immediately and delivered a polished, performant product.",
    projectCompleted: "SaaS Dashboard UI",
    date: "April 2026",
  },
  {
    id: "3",
    clientName: "David Kim",
    rating: 4,
    review: "Great work on our landing page. Sarah's design skills combined with technical expertise made for a smooth project. Would hire again.",
    projectCompleted: "Mobile App Landing Page",
    date: "March 2026",
  },
  {
    id: "4",
    clientName: "Elena Rodriguez",
    rating: 5,
    review: "Sarah created a beautiful design system that our entire team now uses. Her documentation and component library are top-notch.",
    projectCompleted: "Enterprise Design System",
    date: "February 2026",
  },
];

export function getPortfolioItemById(id: string): PortfolioItem | undefined {
  return portfolioItems.find((item) => item.id === id);
}

export const availabilityLabels = {
  available: { label: "Available", color: "bg-green-500" },
  busy: { label: "Busy", color: "bg-amber-500" },
  away: { label: "Away", color: "bg-gray-400" },
} as const;

export const dashboardNavItems = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" as const },
  { label: "AI Proposals", href: "/dashboard/proposals", icon: "Sparkles" as const },
  { label: "Escrow", href: "/dashboard/escrow", icon: "Shield" as const },
  { label: "Portfolio", href: "/dashboard/portfolio", icon: "Briefcase" as const },
  { label: "Find Projects", href: "/projects", icon: "Search" as const },
  { label: "Notifications", href: "/notifications", icon: "Bell" as const },
  { label: "Settings", href: "/settings", icon: "Settings" as const },
] as const;
