import type { FreelancerProfile } from "@/lib/types/freelancer";

const THUMBS = [
  "from-blue-500 to-indigo-600", "from-violet-500 to-purple-600", "from-emerald-500 to-teal-600",
  "from-orange-500 to-amber-600", "from-rose-500 to-pink-600", "from-cyan-500 to-blue-600",
];

function makeDistribution(total: number, avg: number) {
  const dist = [5, 4, 3, 2, 1].map((stars) => ({
    stars,
    count: stars >= Math.round(avg) ? Math.floor(total * (stars === 5 ? 0.55 : 0.15)) : Math.floor(total * 0.05),
  }));
  return dist;
}

export const freelancerProfiles: FreelancerProfile[] = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    avatar: "SC",
    title: "Senior Frontend Developer",
    role: "React Developer",
    location: "San Francisco, US",
    bio: "Building beautiful, performant web applications with React and Next.js for 6+ years.",
    about: "I'm a senior frontend developer passionate about creating exceptional user experiences. I specialize in React ecosystems, design systems, and performance optimization. I've helped startups and enterprises ship products used by millions.",
    experience: "6+ years in frontend development across startups and Fortune 500 companies.",
    specializations: ["React & Next.js", "Design Systems", "Performance Optimization", "E-commerce"],
    careerHighlights: ["Led frontend at Series B startup (acquired)", "Built design system used by 12 teams", "98 Lighthouse scores on 5+ production apps"],
    skills: [
      { name: "React", proficiency: 95 }, { name: "Next.js", proficiency: 90 },
      { name: "TypeScript", proficiency: 92 }, { name: "UI/UX", proficiency: 85 },
    ],
    hourlyRate: 85, jobSuccessScore: 98, rating: 4.9, totalReviews: 47,
    projectsCompleted: 52, availability: "available", responseTime: "< 1 hour",
    experienceLevel: "Expert", languages: ["English", "Mandarin"],
    trustBadges: ["Top Rated", "Verified Identity", "100% Completion", "Fast Response", "Expert Level"],
    lastActive: "Online now",
    portfolio: [
      { id: "p1", title: "FinTech Dashboard", description: "Real-time analytics dashboard", technologies: ["React", "D3.js"], thumbnail: THUMBS[0] },
      { id: "p2", title: "E-commerce Storefront", description: "Premium online store rebuild", technologies: ["Next.js", "Stripe"], thumbnail: THUMBS[1] },
    ],
    workHistory: [
      { id: "w1", projectName: "E-commerce Redesign", client: "Michael Torres", duration: "3 months", earnings: 6500, feedback: "Exceptional work, exceeded expectations.", rating: 5 },
      { id: "w2", projectName: "SaaS Dashboard", client: "Jessica Park", duration: "2 months", earnings: 4200, feedback: "Great communication and quality.", rating: 5 },
    ],
    certifications: [
      { id: "c1", name: "Meta Front-End Developer", provider: "Meta", issueDate: "Jan 2025", credentialId: "META-FE-92847" },
    ],
    reviews: [
      { id: "r1", clientName: "Michael Torres", clientAvatar: "MT", rating: 5, review: "Sarah delivered an exceptional e-commerce redesign. Her attention to detail and communication were outstanding.", projectName: "E-commerce Redesign", projectBudget: "$6,500", date: "May 2026" },
      { id: "r2", clientName: "Jessica Park", clientAvatar: "JP", rating: 5, review: "Working with Sarah was a pleasure. She understood our vision immediately.", projectName: "SaaS Dashboard", projectBudget: "$4,200", date: "Apr 2026" },
    ],
    ratingBreakdown: { communication: 4.9, quality: 4.9, timeliness: 4.8, professionalism: 4.9 },
    ratingDistribution: makeDistribution(47, 4.9),
  },
  {
    id: "marcus-johnson",
    name: "Marcus Johnson",
    avatar: "MJ",
    title: "Full Stack Engineer",
    role: "Node.js Developer",
    location: "New York, US",
    bio: "Full-stack engineer specializing in scalable Node.js backends and React frontends.",
    about: "I build robust, scalable applications from database to deployment. With expertise in Node.js, Python, and cloud infrastructure, I help teams ship reliable products fast.",
    experience: "8+ years building full-stack applications for fintech and SaaS companies.",
    specializations: ["Node.js APIs", "Microservices", "AWS Cloud", "Database Design"],
    careerHighlights: ["Architected API serving 1M+ requests/day", "Reduced infrastructure costs by 40%", "Open source contributor to Express.js"],
    skills: [
      { name: "Node.js", proficiency: 95 }, { name: "Python", proficiency: 88 },
      { name: "React", proficiency: 82 }, { name: "DevOps", proficiency: 80 },
    ],
    hourlyRate: 95, jobSuccessScore: 96, rating: 4.8, totalReviews: 38,
    projectsCompleted: 41, availability: "available", responseTime: "< 2 hours",
    experienceLevel: "Expert", languages: ["English"],
    trustBadges: ["Top Rated", "Verified Identity", "100% Completion", "Expert Level"],
    lastActive: "2 hours ago",
    portfolio: [
      { id: "p1", title: "Payment API", description: "Stripe-integrated payment system", technologies: ["Node.js", "PostgreSQL"], thumbnail: THUMBS[2] },
    ],
    workHistory: [
      { id: "w1", projectName: "Cloud Migration", client: "James Wilson", duration: "4 months", earnings: 10000, feedback: "Expert-level DevOps and backend work.", rating: 5 },
    ],
    certifications: [
      { id: "c1", name: "AWS Certified Developer", provider: "Amazon Web Services", issueDate: "Mar 2025", credentialId: "AWS-DEV-7842" },
    ],
    reviews: [
      { id: "r1", clientName: "James Wilson", clientAvatar: "JW", rating: 5, review: "Marcus handled our cloud migration flawlessly. Zero downtime.", projectName: "Cloud Migration", projectBudget: "$10,000", date: "May 2026" },
    ],
    ratingBreakdown: { communication: 4.7, quality: 4.9, timeliness: 4.8, professionalism: 4.8 },
    ratingDistribution: makeDistribution(38, 4.8),
  },
  {
    id: "elena-rodriguez",
    name: "Elena Rodriguez",
    avatar: "ER",
    title: "Product Designer",
    role: "UI Designer",
    location: "London, UK",
    bio: "Award-winning product designer creating intuitive, beautiful digital experiences.",
    about: "I transform complex problems into elegant, user-centered designs. My work spans mobile apps, web platforms, and design systems for global brands.",
    experience: "5+ years in product design with focus on SaaS and consumer apps.",
    specializations: ["UI/UX Design", "Design Systems", "Prototyping", "User Research"],
    careerHighlights: ["Won regional design award 2025", "Design system adopted by 12 teams", "Increased conversion 35% for e-commerce client"],
    skills: [
      { name: "UI/UX", proficiency: 98 }, { name: "Figma", proficiency: 95 },
      { name: "React", proficiency: 70 }, { name: "TypeScript", proficiency: 65 },
    ],
    hourlyRate: 75, jobSuccessScore: 100, rating: 5.0, totalReviews: 29,
    projectsCompleted: 35, availability: "busy", responseTime: "< 3 hours",
    experienceLevel: "Expert", languages: ["English", "Spanish"],
    trustBadges: ["Top Rated", "Verified Identity", "100% Completion", "Expert Level"],
    lastActive: "1 hour ago",
    portfolio: [
      { id: "p1", title: "Brand Identity", description: "Complete brand system for fintech", technologies: ["Figma", "Illustrator"], thumbnail: THUMBS[3] },
      { id: "p2", title: "Mobile App UI", description: "Fitness app interface design", technologies: ["Figma", "Protopie"], thumbnail: THUMBS[4] },
    ],
    workHistory: [
      { id: "w1", projectName: "Design System", client: "Elena Rodriguez", duration: "2 months", earnings: 3500, feedback: "Beautiful, comprehensive design system.", rating: 5 },
    ],
    certifications: [
      { id: "c1", name: "Google UX Design Certificate", provider: "Google", issueDate: "Sep 2024", credentialId: "GUX-38472" },
    ],
    reviews: [
      { id: "r1", clientName: "David Kim", clientAvatar: "DK", rating: 5, review: "Elena's designs are stunning. She has an incredible eye for detail.", projectName: "Mobile App UI", projectBudget: "$3,500", date: "Jun 2026" },
    ],
    ratingBreakdown: { communication: 5.0, quality: 5.0, timeliness: 4.9, professionalism: 5.0 },
    ratingDistribution: makeDistribution(29, 5.0),
  },
  {
    id: "david-kim",
    name: "David Kim",
    avatar: "DK",
    title: "AI/ML Specialist",
    role: "AI Specialist",
    location: "Toronto, CA",
    bio: "Machine learning engineer building intelligent systems with PyTorch and LLMs.",
    about: "I specialize in building production ML systems — from NLP chatbots to computer vision pipelines. I bridge the gap between research and real-world deployment.",
    experience: "4+ years in ML engineering with PhD in Computer Science.",
    specializations: ["Machine Learning", "NLP", "LLM Integration", "MLOps"],
    careerHighlights: ["Deployed 15+ production ML models", "Published 3 papers on NLP", "Built AI chatbot with 90% resolution rate"],
    skills: [
      { name: "AI", proficiency: 96 }, { name: "Python", proficiency: 95 },
      { name: "Node.js", proficiency: 75 }, { name: "React", proficiency: 70 },
    ],
    hourlyRate: 120, jobSuccessScore: 97, rating: 4.9, totalReviews: 22,
    projectsCompleted: 28, availability: "available", responseTime: "< 2 hours",
    experienceLevel: "Expert", languages: ["English", "Mandarin"],
    trustBadges: ["Top Rated", "Verified Identity", "Expert Level", "Fast Response"],
    lastActive: "30 min ago",
    portfolio: [
      { id: "p1", title: "AI Chatbot", description: "Customer support AI integration", technologies: ["Python", "OpenAI"], thumbnail: THUMBS[5] },
    ],
    workHistory: [
      { id: "w1", projectName: "ML Price Prediction", client: "Robert Chang", duration: "1 month", earnings: 4500, feedback: "Achieved 92% accuracy, exceeded target.", rating: 5 },
    ],
    certifications: [
      { id: "c1", name: "TensorFlow Developer Certificate", provider: "Google", issueDate: "Jun 2024", credentialId: "TF-DEV-28491" },
    ],
    reviews: [
      { id: "r1", clientName: "Robert Chang", clientAvatar: "RC", rating: 5, review: "David's ML expertise is top-notch. Delivered ahead of schedule.", projectName: "ML Model", projectBudget: "$4,500", date: "Jun 2026" },
    ],
    ratingBreakdown: { communication: 4.8, quality: 5.0, timeliness: 4.9, professionalism: 4.9 },
    ratingDistribution: makeDistribution(22, 4.9),
  },
  {
    id: "amira-hassan",
    name: "Amira Hassan",
    avatar: "AH",
    title: "Content Strategist",
    role: "Content Writer",
    location: "Remote",
    bio: "SEO-driven content strategist helping B2B SaaS companies grow organic traffic.",
    about: "I create content strategies that drive measurable results. From blog posts to whitepapers, I help brands establish authority and generate leads.",
    experience: "4+ years in content marketing and SEO for tech companies.",
    specializations: ["SEO Strategy", "Content Marketing", "Copywriting", "Analytics"],
    careerHighlights: ["200% organic traffic growth for SaaS client", "Managed content for 50K+ monthly readers", "10+ featured articles on major publications"],
    skills: [
      { name: "SEO", proficiency: 92 }, { name: "Content", proficiency: 95 },
      { name: "Python", proficiency: 60 }, { name: "React", proficiency: 45 },
    ],
    hourlyRate: 60, jobSuccessScore: 94, rating: 4.7, totalReviews: 31,
    projectsCompleted: 45, availability: "available", responseTime: "< 4 hours",
    experienceLevel: "Intermediate", languages: ["English", "Arabic"],
    trustBadges: ["Verified Identity", "100% Completion", "Rising Talent"],
    lastActive: "3 hours ago",
    portfolio: [
      { id: "p1", title: "SEO Campaign", description: "6-month SEO strategy execution", technologies: ["SEO", "Analytics"], thumbnail: THUMBS[0] },
    ],
    workHistory: [
      { id: "w1", projectName: "Content Marketing", client: "Amira Hassan", duration: "6 months", earnings: 9000, feedback: "Consistent quality content, great results.", rating: 4 },
    ],
    certifications: [],
    reviews: [
      { id: "r1", clientName: "Marcus Johnson", clientAvatar: "MJ", rating: 5, review: "Amira's content strategy doubled our organic traffic.", projectName: "SEO Strategy", projectBudget: "$9,000", date: "Apr 2026" },
    ],
    ratingBreakdown: { communication: 4.8, quality: 4.7, timeliness: 4.6, professionalism: 4.7 },
    ratingDistribution: makeDistribution(31, 4.7),
  },
  {
    id: "james-wilson",
    name: "James Wilson",
    avatar: "JW",
    title: "DevOps Engineer",
    role: "Python Engineer",
    location: "Berlin, DE",
    bio: "DevOps specialist automating infrastructure with Kubernetes, Terraform, and CI/CD.",
    about: "I help teams deploy faster and more reliably. From containerization to monitoring, I build infrastructure that scales.",
    experience: "7+ years in DevOps and cloud infrastructure.",
    specializations: ["Kubernetes", "Terraform", "CI/CD", "AWS/GCP"],
    careerHighlights: ["Zero-downtime migrations for 3 enterprises", "Reduced deploy time from hours to minutes", "Built monitoring for 50+ microservices"],
    skills: [
      { name: "DevOps", proficiency: 96 }, { name: "Python", proficiency: 88 },
      { name: "Node.js", proficiency: 75 }, { name: "React", proficiency: 55 },
    ],
    hourlyRate: 110, jobSuccessScore: 99, rating: 4.9, totalReviews: 26,
    projectsCompleted: 33, availability: "busy", responseTime: "< 1 hour",
    experienceLevel: "Expert", languages: ["English", "German"],
    trustBadges: ["Top Rated", "Verified Identity", "100% Completion", "Expert Level", "Fast Response"],
    lastActive: "Online now",
    portfolio: [
      { id: "p1", title: "K8s Migration", description: "Enterprise Kubernetes migration", technologies: ["Kubernetes", "Terraform"], thumbnail: THUMBS[1] },
    ],
    workHistory: [],
    certifications: [
      { id: "c1", name: "CKA: Certified Kubernetes Administrator", provider: "CNCF", issueDate: "Feb 2025", credentialId: "CKA-2025-4829" },
    ],
    reviews: [
      { id: "r1", clientName: "Michael Torres", clientAvatar: "MT", rating: 5, review: "James is a DevOps wizard. Flawless migration.", projectName: "Cloud Migration", projectBudget: "$12,000", date: "May 2026" },
    ],
    ratingBreakdown: { communication: 4.8, quality: 5.0, timeliness: 4.9, professionalism: 4.9 },
    ratingDistribution: makeDistribution(26, 4.9),
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    avatar: "PS",
    title: "Mobile App Developer",
    role: "React Developer",
    location: "Singapore",
    bio: "Cross-platform mobile developer building polished React Native apps for iOS and Android.",
    about: "I create native-feeling mobile experiences with React Native. From MVPs to production apps, I deliver apps that users love.",
    experience: "5+ years in mobile development across health, fintech, and social apps.",
    specializations: ["React Native", "iOS/Android", "Firebase", "App Store Deployment"],
    careerHighlights: ["50K+ downloads on fitness app MVP", "4.8 App Store rating average", "Published 8 apps to both stores"],
    skills: [
      { name: "React", proficiency: 90 }, { name: "Mobile", proficiency: 95 },
      { name: "Node.js", proficiency: 78 }, { name: "UI/UX", proficiency: 80 },
    ],
    hourlyRate: 80, jobSuccessScore: 95, rating: 4.8, totalReviews: 19,
    projectsCompleted: 24, availability: "available", responseTime: "< 2 hours",
    experienceLevel: "Expert", languages: ["English", "Mandarin"],
    trustBadges: ["Verified Identity", "100% Completion", "Rising Talent", "Fast Response"],
    lastActive: "1 hour ago",
    portfolio: [
      { id: "p1", title: "Fitness App MVP", description: "Cross-platform fitness tracker", technologies: ["React Native", "Firebase"], thumbnail: THUMBS[2] },
    ],
    workHistory: [],
    certifications: [],
    reviews: [
      { id: "r1", clientName: "Jessica Park", clientAvatar: "JP", rating: 5, review: "Priya built our MVP in record time. Highly recommended.", projectName: "Fitness App", projectBudget: "$12,000", date: "Jun 2026" },
    ],
    ratingBreakdown: { communication: 4.9, quality: 4.8, timeliness: 4.7, professionalism: 4.8 },
    ratingDistribution: makeDistribution(19, 4.8),
  },
  {
    id: "alex-rivera",
    name: "Alex Rivera",
    avatar: "AR",
    title: "UI/UX Designer",
    role: "UI Designer",
    location: "Remote",
    bio: "Creative UI designer focused on clean, modern interfaces for web and mobile.",
    about: "I design interfaces that are both beautiful and functional. My process combines user research, wireframing, and high-fidelity prototyping.",
    experience: "3+ years designing for startups and agencies.",
    specializations: ["Web Design", "Mobile UI", "Wireframing", "Design Handoff"],
    careerHighlights: ["Redesigned app with 40% engagement increase", "Featured on Dribbble Top Shots", "Design-to-code workflow expert"],
    skills: [
      { name: "UI/UX", proficiency: 92 }, { name: "Figma", proficiency: 95 },
      { name: "React", proficiency: 65 }, { name: "TypeScript", proficiency: 55 },
    ],
    hourlyRate: 55, jobSuccessScore: 91, rating: 4.6, totalReviews: 15,
    projectsCompleted: 18, availability: "available", responseTime: "< 3 hours",
    experienceLevel: "Intermediate", languages: ["English", "Spanish"],
    trustBadges: ["Verified Identity", "Rising Talent"],
    lastActive: "5 hours ago",
    portfolio: [
      { id: "p1", title: "UI Audit", description: "Dashboard UX redesign", technologies: ["Figma"], thumbnail: THUMBS[3] },
    ],
    workHistory: [],
    certifications: [],
    reviews: [
      { id: "r1", clientName: "Lisa Thompson", clientAvatar: "LT", rating: 4, review: "Good design work, delivered on time.", projectName: "UI Audit", projectBudget: "$500", date: "Jun 2026" },
    ],
    ratingBreakdown: { communication: 4.7, quality: 4.6, timeliness: 4.5, professionalism: 4.6 },
    ratingDistribution: makeDistribution(15, 4.6),
  },
  {
    id: "nina-patel",
    name: "Nina Patel",
    avatar: "NP",
    title: "Backend Developer",
    role: "Python Engineer",
    location: "San Francisco, US",
    bio: "Backend engineer building scalable APIs with Python, Django, and PostgreSQL.",
    about: "I architect and build robust backend systems. Specializing in RESTful APIs, database optimization, and payment integrations.",
    experience: "5+ years in backend development for e-commerce and fintech.",
    specializations: ["Python/Django", "API Design", "Payment Integration", "Database Optimization"],
    careerHighlights: ["Built API handling 500K daily transactions", "Stripe & PayPal integration expert", "Reduced query time by 80%"],
    skills: [
      { name: "Python", proficiency: 94 }, { name: "Node.js", proficiency: 80 },
      { name: "React", proficiency: 68 }, { name: "DevOps", proficiency: 72 },
    ],
    hourlyRate: 90, jobSuccessScore: 97, rating: 4.8, totalReviews: 24,
    projectsCompleted: 30, availability: "available", responseTime: "< 2 hours",
    experienceLevel: "Expert", languages: ["English"],
    trustBadges: ["Top Rated", "Verified Identity", "100% Completion", "Expert Level"],
    lastActive: "2 hours ago",
    portfolio: [
      { id: "p1", title: "Payment Integration", description: "Stripe & PayPal API integration", technologies: ["Python", "Node.js"], thumbnail: THUMBS[4] },
    ],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.8, quality: 4.9, timeliness: 4.7, professionalism: 4.8 },
    ratingDistribution: makeDistribution(24, 4.8),
  },
  {
    id: "tom-anderson",
    name: "Tom Anderson",
    avatar: "TA",
    title: "WordPress Developer",
    role: "React Developer",
    location: "Sydney, AU",
    bio: "WordPress and headless CMS developer creating fast, SEO-friendly websites.",
    about: "I build WordPress sites and headless CMS solutions that are fast, secure, and easy to manage. Custom themes, plugins, and migrations.",
    experience: "6+ years in WordPress development and CMS solutions.",
    specializations: ["WordPress", "Headless CMS", "SEO", "Performance"],
    careerHighlights: ["200+ WordPress sites delivered", "Average PageSpeed score 95+", "Custom plugin with 5K+ installs"],
    skills: [
      { name: "React", proficiency: 78 }, { name: "Next.js", proficiency: 75 },
      { name: "SEO", proficiency: 88 }, { name: "Node.js", proficiency: 70 },
    ],
    hourlyRate: 65, jobSuccessScore: 93, rating: 4.7, totalReviews: 42,
    projectsCompleted: 78, availability: "away", responseTime: "< 6 hours",
    experienceLevel: "Expert", languages: ["English"],
    trustBadges: ["Verified Identity", "100% Completion"],
    lastActive: "1 day ago",
    portfolio: [],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.6, quality: 4.7, timeliness: 4.5, professionalism: 4.7 },
    ratingDistribution: makeDistribution(42, 4.7),
  },
  {
    id: "yuki-tanaka",
    name: "Yuki Tanaka",
    avatar: "YT",
    title: "Data Scientist",
    role: "Python Engineer",
    location: "Remote",
    bio: "Data scientist turning complex datasets into actionable business insights.",
    about: "I help companies make data-driven decisions through analytics, visualization, and predictive modeling.",
    experience: "4+ years in data science across e-commerce and healthcare.",
    specializations: ["Data Analysis", "Visualization", "Predictive Modeling", "SQL"],
    careerHighlights: ["Built recommendation engine increasing sales 25%", "Automated reporting saving 20hrs/week", "Published data insights blog with 10K readers"],
    skills: [
      { name: "Python", proficiency: 93 }, { name: "AI", proficiency: 85 },
      { name: "React", proficiency: 60 }, { name: "Node.js", proficiency: 55 },
    ],
    hourlyRate: 85, jobSuccessScore: 96, rating: 4.8, totalReviews: 17,
    projectsCompleted: 22, availability: "available", responseTime: "< 3 hours",
    experienceLevel: "Expert", languages: ["English", "Mandarin"],
    trustBadges: ["Verified Identity", "Expert Level", "Fast Response"],
    lastActive: "4 hours ago",
    portfolio: [],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.7, quality: 4.9, timeliness: 4.8, professionalism: 4.8 },
    ratingDistribution: makeDistribution(17, 4.8),
  },
  {
    id: "sofia-martinez",
    name: "Sofia Martinez",
    avatar: "SM",
    title: "Marketing Specialist",
    role: "Content Writer",
    location: "Remote",
    bio: "Digital marketing specialist driving growth through social media and paid campaigns.",
    about: "I create and execute marketing strategies that generate leads and build brand awareness across social platforms.",
    experience: "3+ years in digital marketing for tech startups.",
    specializations: ["Social Media", "Paid Ads", "Email Marketing", "Analytics"],
    careerHighlights: ["55% campaign engagement increase", "Managed $50K+ ad budgets", "Built email list to 20K subscribers"],
    skills: [
      { name: "SEO", proficiency: 85 }, { name: "Content", proficiency: 90 },
      { name: "React", proficiency: 40 }, { name: "UI/UX", proficiency: 70 },
    ],
    hourlyRate: 45, jobSuccessScore: 90, rating: 4.5, totalReviews: 12,
    projectsCompleted: 20, availability: "available", responseTime: "< 4 hours",
    experienceLevel: "Intermediate", languages: ["English", "Spanish", "Portuguese"],
    trustBadges: ["Verified Identity", "Rising Talent"],
    lastActive: "6 hours ago",
    portfolio: [],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.6, quality: 4.5, timeliness: 4.4, professionalism: 4.5 },
    ratingDistribution: makeDistribution(12, 4.5),
  },
  {
    id: "ryan-oconnor",
    name: "Ryan O'Connor",
    avatar: "RO",
    title: "Blockchain Developer",
    role: "Python Engineer",
    location: "London, UK",
    bio: "Blockchain developer building DeFi protocols and smart contracts on Ethereum.",
    about: "I develop secure smart contracts and decentralized applications. Audited 10+ contracts with zero vulnerabilities.",
    experience: "3+ years in blockchain and Web3 development.",
    specializations: ["Solidity", "DeFi", "Smart Contracts", "Web3"],
    careerHighlights: ["Deployed 5 DeFi protocols", "Zero vulnerabilities in audits", "Open source Web3 library contributor"],
    skills: [
      { name: "Python", proficiency: 88 }, { name: "Node.js", proficiency: 85 },
      { name: "React", proficiency: 75 }, { name: "AI", proficiency: 60 },
    ],
    hourlyRate: 130, jobSuccessScore: 95, rating: 4.7, totalReviews: 11,
    projectsCompleted: 15, availability: "busy", responseTime: "< 2 hours",
    experienceLevel: "Expert", languages: ["English"],
    trustBadges: ["Verified Identity", "Expert Level"],
    lastActive: "3 hours ago",
    portfolio: [],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.6, quality: 4.8, timeliness: 4.5, professionalism: 4.7 },
    ratingDistribution: makeDistribution(11, 4.7),
  },
  {
    id: "lisa-thompson",
    name: "Lisa Thompson",
    avatar: "LT",
    title: "QA Engineer",
    role: "Python Engineer",
    location: "New York, US",
    bio: "QA engineer ensuring software quality through automated testing and CI/CD integration.",
    about: "I build comprehensive test suites and QA processes that catch bugs before they reach production.",
    experience: "4+ years in QA automation for web and mobile applications.",
    specializations: ["Test Automation", "Selenium/Cypress", "CI/CD Testing", "Performance Testing"],
    careerHighlights: ["Reduced production bugs by 70%", "Built test suite with 95% coverage", "Performance testing for 1M+ user app"],
    skills: [
      { name: "Python", proficiency: 85 }, { name: "DevOps", proficiency: 78 },
      { name: "React", proficiency: 65 }, { name: "Node.js", proficiency: 70 },
    ],
    hourlyRate: 70, jobSuccessScore: 98, rating: 4.9, totalReviews: 20,
    projectsCompleted: 27, availability: "available", responseTime: "< 1 hour",
    experienceLevel: "Intermediate", languages: ["English"],
    trustBadges: ["Top Rated", "Verified Identity", "100% Completion", "Fast Response"],
    lastActive: "Online now",
    portfolio: [],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.9, quality: 4.9, timeliness: 4.8, professionalism: 4.9 },
    ratingDistribution: makeDistribution(20, 4.9),
  },
  {
    id: "chen-wei",
    name: "Chen Wei",
    avatar: "CW",
    title: "Junior Full Stack Developer",
    role: "React Developer",
    location: "Remote",
    bio: "Motivated full-stack developer eager to deliver quality work on React and Node.js projects.",
    about: "Recent bootcamp graduate with strong fundamentals in React, Node.js, and modern web development. Quick learner with passion for clean code.",
    experience: "1+ year freelance and internship experience.",
    specializations: ["React", "Node.js", "REST APIs", "Responsive Design"],
    careerHighlights: ["Completed 8 freelance projects with 5-star ratings", "Built 3 full-stack apps from scratch"],
    skills: [
      { name: "React", proficiency: 82 }, { name: "Next.js", proficiency: 78 },
      { name: "Node.js", proficiency: 75 }, { name: "TypeScript", proficiency: 80 },
    ],
    hourlyRate: 35, jobSuccessScore: 88, rating: 4.6, totalReviews: 8,
    projectsCompleted: 10, availability: "available", responseTime: "< 2 hours",
    experienceLevel: "Beginner", languages: ["English", "Mandarin"],
    trustBadges: ["Verified Identity", "Rising Talent", "Fast Response"],
    lastActive: "1 hour ago",
    portfolio: [],
    workHistory: [],
    certifications: [],
    reviews: [],
    ratingBreakdown: { communication: 4.7, quality: 4.5, timeliness: 4.6, professionalism: 4.6 },
    ratingDistribution: makeDistribution(8, 4.6),
  },
];


export function getFreelancerById(id: string): FreelancerProfile | undefined {
  return freelancerProfiles.find((f) => f.id === id);
}

export function getFreelancersByIds(ids: string[]): FreelancerProfile[] {
  return ids.map((id) => getFreelancerById(id)).filter(Boolean) as FreelancerProfile[];
}

export const recommendedFreelancers = [
  { freelancerId: "sarah-chen", reason: "Best Match for React Projects", highlight: "98% skill match" },
  { freelancerId: "elena-rodriguez", reason: "Strong UI/UX Experience", highlight: "5.0 rating" },
  { freelancerId: "david-kim", reason: "High Success Rate", highlight: "97% job success" },
  { freelancerId: "james-wilson", reason: "Expert DevOps Skills", highlight: "99% completion" },
];

export const mockConversations = [
  { id: "c1", name: "Michael Torres", avatar: "MT", lastMessage: "Can you start next Monday?", time: "2h ago", unread: true },
  { id: "c2", name: "Jessica Park", avatar: "JP", lastMessage: "The designs look great!", time: "5h ago", unread: false },
  { id: "c3", name: "David Kim", avatar: "DK", lastMessage: "Let's schedule a call.", time: "1d ago", unread: false },
];
