import type { AppNotification } from "@/lib/types/settings";

export const mockNotifications: AppNotification[] = [
  {
    id: "n1",
    category: "projects",
    priority: "high",
    status: "unread",
    title: "New Project Match",
    description: "React E-commerce Redesign — 98% skill match based on your profile.",
    timestamp: "5 min ago",
    actionLabel: "View Project",
    actionHref: "/projects/ecommerce-redesign",
    icon: "Briefcase",
  },
  {
    id: "n2",
    category: "proposals",
    priority: "high",
    status: "unread",
    title: "Proposal Accepted",
    description: "Your proposal for SaaS Dashboard UI was accepted by Jessica Park.",
    timestamp: "1 hour ago",
    actionLabel: "View Details",
    actionHref: "/dashboard/proposals",
    icon: "FileCheck",
  },
  {
    id: "n3",
    category: "payments",
    priority: "medium",
    status: "unread",
    title: "Payment Released",
    description: "$2,500 released from escrow for Milestone 2 — E-commerce Redesign.",
    timestamp: "3 hours ago",
    actionLabel: "View Receipt",
    actionHref: "/dashboard/escrow/receipts/RCP-0042",
    icon: "DollarSign",
  },
  {
    id: "n4",
    category: "payments",
    priority: "medium",
    status: "read",
    title: "Milestone Approved",
    description: "Client approved Milestone 1 for Mobile App MVP project.",
    timestamp: "Yesterday",
    actionLabel: "View Contract",
    actionHref: "/dashboard/escrow/contracts/esc-001",
    icon: "CheckCircle",
  },
  {
    id: "n5",
    category: "messages",
    priority: "high",
    status: "unread",
    title: "Client Message",
    description: "Michael Torres: \"Can you start the redesign next Monday?\"",
    timestamp: "2 hours ago",
    actionLabel: "Reply",
    actionHref: "/freelancers",
    icon: "MessageSquare",
  },
  {
    id: "n6",
    category: "messages",
    priority: "low",
    status: "read",
    title: "New Message",
    description: "David Kim sent you a message about the AI chatbot project.",
    timestamp: "2 days ago",
    actionLabel: "View Message",
    actionHref: "/freelancers",
    icon: "MessageSquare",
  },
  {
    id: "n7",
    category: "proposals",
    priority: "medium",
    status: "read",
    title: "Proposal Viewed",
    description: "Your proposal for Brand Identity Package was viewed by the client.",
    timestamp: "3 days ago",
    actionLabel: "View Proposal",
    actionHref: "/dashboard/proposals/saved",
    icon: "Eye",
  },
  {
    id: "n8",
    category: "projects",
    priority: "low",
    status: "read",
    title: "Project Recommendation",
    description: "3 new projects match your React and TypeScript skills.",
    timestamp: "4 days ago",
    actionLabel: "Browse Projects",
    actionHref: "/projects",
    icon: "Sparkles",
  },
  {
    id: "n9",
    category: "system",
    priority: "low",
    status: "read",
    title: "System Update",
    description: "FreelanceAI v2.1 — New AI proposal scoring and escrow analytics.",
    timestamp: "1 week ago",
    actionLabel: "Learn More",
    actionHref: "/#ai-features",
    icon: "Bell",
  },
  {
    id: "n10",
    category: "system",
    priority: "medium",
    status: "read",
    title: "Security Alert",
    description: "New login detected from Chrome on Linux. Was this you?",
    timestamp: "1 week ago",
    actionLabel: "Review Sessions",
    actionHref: "/settings?section=security",
    icon: "Shield",
  },
  {
    id: "n11",
    category: "payments",
    priority: "high",
    status: "read",
    title: "Escrow Funded",
    description: "$8,000 deposited into escrow for Cloud Migration project.",
    timestamp: "2 weeks ago",
    actionLabel: "View Escrow",
    actionHref: "/dashboard/escrow",
    icon: "Wallet",
  },
  {
    id: "n12",
    category: "proposals",
    priority: "low",
    status: "read",
    title: "Proposal Reminder",
    description: "You have a draft proposal for FinTech Dashboard. Finish and submit?",
    timestamp: "2 weeks ago",
    actionLabel: "Continue",
    actionHref: "/dashboard/proposals",
    icon: "PenLine",
  },
];

export const accountData = {
  email: "sarah.chen@email.com",
  username: "sarahchen",
  accountStatus: "Active",
  membershipType: "Pro Freelancer",
  memberSince: "March 2024",
  stats: {
    projectsCompleted: 52,
    totalEarnings: "$124,500",
    clientRating: 4.9,
    responseRate: "98%",
  },
};

export const loginSessions = [
  {
    id: "s1",
    device: "Chrome on Linux",
    location: "San Francisco, US",
    lastActive: "Active now",
    current: true,
  },
  {
    id: "s2",
    device: "Safari on iPhone 15",
    location: "San Francisco, US",
    lastActive: "2 days ago",
    current: false,
  },
  {
    id: "s3",
    device: "Firefox on Windows",
    location: "New York, US",
    lastActive: "1 week ago",
    current: false,
  },
];

export const recentDevices = [
  { id: "d1", name: "MacBook Pro 14\"", lastUsed: "Today", trusted: true },
  { id: "d2", name: "iPhone 15 Pro", lastUsed: "2 days ago", trusted: true },
  { id: "d3", name: "Windows Desktop", lastUsed: "1 week ago", trusted: false },
];
