import type { MarketplaceProject } from "@/lib/types/project";

export const marketplaceProjects: MarketplaceProject[] = [
  {
    id: "ecommerce-redesign",
    title: "E-commerce Platform Redesign",
    budget: "$5,000 – $8,000",
    budgetMin: 5000,
    budgetMax: 8000,
    postedAt: "2026-06-10T14:30:00Z",
    postedTime: "2 days ago",
    description:
      "Redesign and rebuild a modern e-commerce storefront with improved UX, faster load times, and mobile-first responsive design.",
    skills: ["React", "Next.js", "UI/UX"],
    experienceLevel: "Expert",
    proposalCount: 24,
    clientRating: 4.9,
    category: "Web Development",
    projectType: "Fixed Price",
    duration: "1-3 months",
    budgetRange: "1000-plus",
    overview:
      "We're a growing D2C brand looking to completely overhaul our online store. The current platform is outdated, slow, and doesn't reflect our premium brand identity. We need a developer who can deliver a pixel-perfect, high-performance storefront.",
    objectives: [
      "Redesign all customer-facing pages with a modern, premium aesthetic",
      "Improve page load times to under 2 seconds on mobile",
      "Implement a seamless checkout flow with cart abandonment recovery",
      "Integrate with our existing Shopify backend and inventory system",
    ],
    deliverables: [
      "Fully responsive Next.js storefront",
      "Component library and design system documentation",
      "Performance audit report with before/after metrics",
      "30 days of post-launch bug fix support",
    ],
    timeline: "Expected start: July 2026. Duration: 8–10 weeks with weekly milestone reviews.",
    client: {
      name: "Michael Torres",
      rating: 4.9,
      totalProjectsPosted: 18,
      memberSince: "March 2023",
      verified: true,
      avatar: "MT",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 10, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 10 – Jun 24", status: "current" },
      { label: "Selection", date: "Jun 25 – Jun 28", status: "upcoming" },
      { label: "Project Start", date: "Jul 1, 2026", status: "upcoming" },
    ],
  },
  {
    id: "mobile-app-mvp",
    title: "Fitness Tracking Mobile App MVP",
    budget: "$10,000 – $15,000",
    budgetMin: 10000,
    budgetMax: 15000,
    postedAt: "2026-06-11T09:00:00Z",
    postedTime: "1 day ago",
    description:
      "Build a cross-platform mobile app MVP for a fitness tracking startup with workout logging, progress charts, and social features.",
    skills: ["React", "Node.js", "UI/UX"],
    experienceLevel: "Expert",
    proposalCount: 31,
    clientRating: 4.7,
    category: "Mobile Apps",
    projectType: "Fixed Price",
    duration: "1-3 months",
    budgetRange: "1000-plus",
    overview:
      "FitPulse is an early-stage startup building the next generation of fitness tracking. We need an experienced mobile developer to build our MVP for iOS and Android using React Native.",
    objectives: [
      "Develop cross-platform app with workout logging and exercise library",
      "Build progress tracking with charts and personal records",
      "Implement user authentication and profile management",
      "Create a social feed for sharing workout achievements",
    ],
    deliverables: [
      "React Native app for iOS and Android",
      "Node.js backend API with PostgreSQL database",
      "Admin dashboard for content management",
      "App Store and Play Store submission support",
    ],
    timeline: "12-week development cycle with bi-weekly sprint demos.",
    client: {
      name: "Jessica Park",
      rating: 4.7,
      totalProjectsPosted: 5,
      memberSince: "January 2025",
      verified: true,
      avatar: "JP",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 11, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 11 – Jun 25", status: "current" },
      { label: "Selection", date: "Jun 26 – Jun 30", status: "upcoming" },
      { label: "Project Start", date: "Jul 3, 2026", status: "upcoming" },
    ],
  },
  {
    id: "brand-identity",
    title: "Brand Identity & Logo Design",
    budget: "$2,000 – $3,500",
    budgetMin: 2000,
    budgetMax: 3500,
    postedAt: "2026-06-09T16:00:00Z",
    postedTime: "3 days ago",
    description:
      "Create a complete brand identity including logo, color palette, typography, and style guide for a sustainable fashion startup.",
    skills: ["UI/UX"],
    experienceLevel: "Intermediate",
    proposalCount: 18,
    clientRating: 5.0,
    category: "Design",
    projectType: "Fixed Price",
    duration: "1-4 weeks",
    budgetRange: "1000-plus",
    overview:
      "EcoThread is launching a sustainable fashion line and needs a cohesive brand identity that communicates eco-consciousness, quality, and modern style.",
    objectives: [
      "Design a memorable, versatile logo with multiple variations",
      "Develop a cohesive color palette and typography system",
      "Create brand guidelines document for consistent application",
      "Design business cards, social media templates, and packaging mockups",
    ],
    deliverables: [
      "Primary and secondary logo files (SVG, PNG, AI)",
      "Brand style guide PDF (20+ pages)",
      "Social media template pack",
      "Packaging design mockups",
    ],
    timeline: "3-week project with concept presentation in week 1.",
    client: {
      name: "Elena Rodriguez",
      rating: 5.0,
      totalProjectsPosted: 8,
      memberSince: "August 2024",
      verified: true,
      avatar: "ER",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 9, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 9 – Jun 23", status: "current" },
      { label: "Selection", date: "Jun 24 – Jun 26", status: "upcoming" },
      { label: "Project Start", date: "Jun 30, 2026", status: "upcoming" },
    ],
  },
  {
    id: "ai-chatbot",
    title: "AI Customer Support Chatbot",
    budget: "$4,000 – $6,000",
    budgetMin: 4000,
    budgetMax: 6000,
    postedAt: "2026-06-12T08:00:00Z",
    postedTime: "6 hours ago",
    description:
      "Integrate an AI-powered customer support chatbot into an existing SaaS web application with knowledge base training.",
    skills: ["AI", "Python", "Node.js"],
    experienceLevel: "Expert",
    proposalCount: 12,
    clientRating: 4.8,
    category: "AI",
    projectType: "Fixed Price",
    duration: "1-4 weeks",
    budgetRange: "1000-plus",
    overview:
      "Our SaaS platform handles 500+ support tickets daily. We want to reduce response times by 70% with an intelligent chatbot that learns from our documentation.",
    objectives: [
      "Build chatbot widget embeddable in our React application",
      "Train on existing knowledge base and support ticket history",
      "Implement human handoff for complex queries",
      "Set up analytics dashboard for bot performance tracking",
    ],
    deliverables: [
      "Production-ready chatbot integration",
      "Admin panel for knowledge base management",
      "Performance analytics dashboard",
      "Documentation and training guide for support team",
    ],
    timeline: "4-week implementation with testing in week 4.",
    client: {
      name: "David Kim",
      rating: 4.8,
      totalProjectsPosted: 12,
      memberSince: "June 2023",
      verified: true,
      avatar: "DK",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 12, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 12 – Jun 26", status: "current" },
      { label: "Selection", date: "Jun 27 – Jun 29", status: "upcoming" },
      { label: "Project Start", date: "Jul 2, 2026", status: "upcoming" },
    ],
  },
  {
    id: "seo-content",
    title: "SEO & Content Marketing Strategy",
    budget: "$1,500 – $2,500/mo",
    budgetMin: 1500,
    budgetMax: 2500,
    postedAt: "2026-06-08T11:00:00Z",
    postedTime: "4 days ago",
    description:
      "Develop and execute an SEO strategy with monthly content creation, keyword research, and performance reporting for a B2B SaaS company.",
    skills: ["AI"],
    experienceLevel: "Intermediate",
    proposalCount: 15,
    clientRating: 4.6,
    category: "Marketing",
    projectType: "Hourly",
    duration: "3+ months",
    budgetRange: "1000-plus",
    overview:
      "CloudMetrics needs to increase organic traffic by 150% over the next 6 months. We're looking for an SEO specialist who understands B2B SaaS marketing.",
    objectives: [
      "Conduct comprehensive SEO audit and competitor analysis",
      "Develop content calendar with 8 articles per month",
      "Optimize existing pages for target keywords",
      "Build quality backlinks through outreach and guest posting",
    ],
    deliverables: [
      "Monthly SEO performance reports",
      "8 optimized blog articles per month",
      "Keyword ranking tracker dashboard",
      "Quarterly strategy review and recommendations",
    ],
    timeline: "Ongoing 6-month engagement with monthly reviews.",
    client: {
      name: "Amira Hassan",
      rating: 4.6,
      totalProjectsPosted: 6,
      memberSince: "November 2024",
      verified: false,
      avatar: "AH",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 8, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 8 – Jun 22", status: "current" },
      { label: "Selection", date: "Jun 23 – Jun 25", status: "upcoming" },
      { label: "Project Start", date: "Jun 30, 2026", status: "upcoming" },
    ],
  },
  {
    id: "cloud-migration",
    title: "Cloud Infrastructure Migration to AWS",
    budget: "$8,000 – $12,000",
    budgetMin: 8000,
    budgetMax: 12000,
    postedAt: "2026-06-07T13:00:00Z",
    postedTime: "5 days ago",
    description:
      "Migrate legacy on-premise infrastructure to AWS with zero-downtime deployment, CI/CD pipeline, and monitoring setup.",
    skills: ["Node.js", "Python"],
    experienceLevel: "Expert",
    proposalCount: 9,
    clientRating: 4.9,
    category: "Web Development",
    projectType: "Fixed Price",
    duration: "1-3 months",
    budgetRange: "1000-plus",
    overview:
      "Our fintech application currently runs on aging on-premise servers. We need a DevOps expert to plan and execute a full AWS migration with minimal disruption.",
    objectives: [
      "Audit current infrastructure and create migration plan",
      "Set up AWS environment with VPC, ECS, RDS, and S3",
      "Implement CI/CD pipeline with GitHub Actions",
      "Configure monitoring, alerting, and auto-scaling",
    ],
    deliverables: [
      "Migration runbook and rollback procedures",
      "Fully configured AWS infrastructure as code (Terraform)",
      "CI/CD pipeline with automated testing",
      "Monitoring dashboard and incident response playbook",
    ],
    timeline: "10-week migration with phased rollout starting week 6.",
    client: {
      name: "James Wilson",
      rating: 4.9,
      totalProjectsPosted: 22,
      memberSince: "February 2022",
      verified: true,
      avatar: "JW",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 7, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 7 – Jun 21", status: "current" },
      { label: "Selection", date: "Jun 22 – Jun 25", status: "upcoming" },
      { label: "Project Start", date: "Jun 28, 2026", status: "upcoming" },
    ],
  },
  {
    id: "landing-page",
    title: "SaaS Landing Page Development",
    budget: "$800 – $1,200",
    budgetMin: 800,
    budgetMax: 1200,
    postedAt: "2026-06-12T10:00:00Z",
    postedTime: "4 hours ago",
    description:
      "Build a high-converting landing page for a project management SaaS with animations, testimonials section, and pricing table.",
    skills: ["React", "Next.js", "UI/UX"],
    experienceLevel: "Intermediate",
    proposalCount: 27,
    clientRating: 4.5,
    category: "Web Development",
    projectType: "Fixed Price",
    duration: "1-4 weeks",
    budgetRange: "500-1000",
    overview:
      "TaskFlow needs a stunning landing page to support our Product Hunt launch. The page should clearly communicate our value proposition and drive sign-ups.",
    objectives: [
      "Design and build a responsive landing page in Next.js",
      "Implement smooth scroll animations and micro-interactions",
      "Create pricing comparison table with toggle",
      "Optimize for Core Web Vitals and conversion rate",
    ],
    deliverables: [
      "Production-ready Next.js landing page",
      "Mobile-responsive design across all breakpoints",
      "Analytics integration (Google Analytics, Hotjar)",
      "A/B test-ready component variants",
    ],
    timeline: "2-week sprint with design approval in first 3 days.",
    client: {
      name: "Sarah Chen",
      rating: 4.5,
      totalProjectsPosted: 3,
      memberSince: "April 2026",
      verified: true,
      avatar: "SC",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 12, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 12 – Jun 19", status: "current" },
      { label: "Selection", date: "Jun 20 – Jun 21", status: "upcoming" },
      { label: "Project Start", date: "Jun 23, 2026", status: "upcoming" },
    ],
  },
  {
    id: "blog-writer",
    title: "Technical Blog Writer — React & Next.js",
    budget: "$50 – $80 per article",
    budgetMin: 50,
    budgetMax: 80,
    postedAt: "2026-06-11T15:00:00Z",
    postedTime: "23 hours ago",
    description:
      "Write 4 in-depth technical blog posts per month about React, Next.js, and modern web development for a developer education platform.",
    skills: ["React", "Next.js"],
    experienceLevel: "Intermediate",
    proposalCount: 42,
    clientRating: 4.7,
    category: "Writing",
    projectType: "Hourly",
    duration: "3+ months",
    budgetRange: "100-500",
    overview:
      "DevLearn publishes high-quality technical content for 50K+ developers. We need a writer who can create engaging, accurate tutorials and deep dives.",
    objectives: [
      "Write 4 technical articles per month (1500–2500 words each)",
      "Include working code examples and interactive demos",
      "Optimize content for SEO with proper heading structure",
      "Collaborate with our editorial team on topic selection",
    ],
    deliverables: [
      "4 published articles per month",
      "Code repositories for each tutorial",
      "Social media snippets for promotion",
      "Monthly content performance report",
    ],
    timeline: "Ongoing monthly engagement starting immediately.",
    client: {
      name: "Marcus Johnson",
      rating: 4.7,
      totalProjectsPosted: 15,
      memberSince: "May 2023",
      verified: true,
      avatar: "MJ",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 11, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 11 – Jun 18", status: "current" },
      { label: "Selection", date: "Jun 19 – Jun 20", status: "upcoming" },
      { label: "Project Start", date: "Jun 22, 2026", status: "upcoming" },
    ],
  },
  {
    id: "ui-audit",
    title: "UI/UX Audit & Redesign Recommendations",
    budget: "$300 – $500",
    budgetMin: 300,
    budgetMax: 500,
    postedAt: "2026-06-10T18:00:00Z",
    postedTime: "2 days ago",
    description:
      "Conduct a comprehensive UI/UX audit of our web application and deliver actionable redesign recommendations with wireframes.",
    skills: ["UI/UX"],
    experienceLevel: "Intermediate",
    proposalCount: 21,
    clientRating: 4.4,
    category: "Design",
    projectType: "Fixed Price",
    duration: "Less than 1 week",
    budgetRange: "100-500",
    overview:
      "Our analytics dashboard has grown organically and the UX has become confusing. We need an expert eye to identify pain points and propose improvements.",
    objectives: [
      "Audit all major user flows and identify friction points",
      "Analyze competitor dashboards for best practices",
      "Create wireframes for top 5 recommended improvements",
      "Present findings with prioritized action items",
    ],
    deliverables: [
      "UX audit report (PDF, 15+ pages)",
      "User flow diagrams with annotated issues",
      "Wireframes for recommended redesigns",
      "30-minute presentation walkthrough",
    ],
    timeline: "1-week turnaround from project start.",
    client: {
      name: "Lisa Thompson",
      rating: 4.4,
      totalProjectsPosted: 4,
      memberSince: "February 2026",
      verified: false,
      avatar: "LT",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 10, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 10 – Jun 17", status: "current" },
      { label: "Selection", date: "Jun 18", status: "upcoming" },
      { label: "Project Start", date: "Jun 20, 2026", status: "upcoming" },
    ],
  },
  {
    id: "ml-model",
    title: "Machine Learning Model for Price Prediction",
    budget: "$3,000 – $5,000",
    budgetMin: 3000,
    budgetMax: 5000,
    postedAt: "2026-06-09T10:00:00Z",
    postedTime: "3 days ago",
    description:
      "Build and deploy a machine learning model to predict real estate prices using historical data with 90%+ accuracy target.",
    skills: ["AI", "Python"],
    experienceLevel: "Expert",
    proposalCount: 8,
    clientRating: 4.8,
    category: "AI",
    projectType: "Fixed Price",
    duration: "1-4 weeks",
    budgetRange: "1000-plus",
    overview:
      "PropInsight is a real estate analytics platform. We need an ML engineer to develop a price prediction model trained on 5 years of regional sales data.",
    objectives: [
      "Clean and preprocess 500K+ property records",
      "Train and evaluate multiple ML models (XGBoost, Random Forest, Neural Net)",
      "Achieve 90%+ prediction accuracy on test set",
      "Deploy model as REST API with documentation",
    ],
    deliverables: [
      "Trained ML model with evaluation metrics",
      "REST API endpoint for predictions",
      "Jupyter notebook with full analysis pipeline",
      "Model documentation and retraining guide",
    ],
    timeline: "4-week project with model demo in week 3.",
    client: {
      name: "Robert Chang",
      rating: 4.8,
      totalProjectsPosted: 9,
      memberSince: "September 2023",
      verified: true,
      avatar: "RC",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 9, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 9 – Jun 23", status: "current" },
      { label: "Selection", date: "Jun 24 – Jun 26", status: "upcoming" },
      { label: "Project Start", date: "Jun 30, 2026", status: "upcoming" },
    ],
  },
  {
    id: "api-integration",
    title: "Stripe & PayPal Payment Integration",
    budget: "$600 – $900",
    budgetMin: 600,
    budgetMax: 900,
    postedAt: "2026-06-12T06:00:00Z",
    postedTime: "8 hours ago",
    description:
      "Integrate Stripe and PayPal payment gateways into an existing Node.js e-commerce backend with subscription support.",
    skills: ["Node.js", "React"],
    experienceLevel: "Intermediate",
    proposalCount: 16,
    clientRating: 4.6,
    category: "Web Development",
    projectType: "Fixed Price",
    duration: "1-4 weeks",
    budgetRange: "500-1000",
    overview:
      "Our online marketplace needs to accept both one-time payments and recurring subscriptions. We have the backend scaffold ready and need payment integration expertise.",
    objectives: [
      "Integrate Stripe for card payments and subscriptions",
      "Add PayPal as alternative payment method",
      "Implement webhook handlers for payment events",
      "Build admin dashboard for transaction monitoring",
    ],
    deliverables: [
      "Working Stripe and PayPal integrations",
      "Webhook event handling with retry logic",
      "Transaction monitoring dashboard",
      "Integration test suite and documentation",
    ],
    timeline: "3-week implementation with sandbox testing in week 2.",
    client: {
      name: "Nina Patel",
      rating: 4.6,
      totalProjectsPosted: 7,
      memberSince: "July 2024",
      verified: true,
      avatar: "NP",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 12, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 12 – Jun 19", status: "current" },
      { label: "Selection", date: "Jun 20 – Jun 21", status: "upcoming" },
      { label: "Project Start", date: "Jun 23, 2026", status: "upcoming" },
    ],
  },
  {
    id: "social-media",
    title: "Social Media Content Creation",
    budget: "$25 – $50 per post",
    budgetMin: 25,
    budgetMax: 50,
    postedAt: "2026-06-11T12:00:00Z",
    postedTime: "1 day ago",
    description:
      "Create engaging social media content for Instagram, LinkedIn, and Twitter for a tech startup — 12 posts per month with graphics.",
    skills: ["UI/UX"],
    experienceLevel: "Beginner",
    proposalCount: 35,
    clientRating: 4.3,
    category: "Marketing",
    projectType: "Hourly",
    duration: "3+ months",
    budgetRange: "under-100",
    overview:
      "TechNova is a B2B SaaS startup looking to build their social media presence. We need creative content that resonates with developers and tech leaders.",
    objectives: [
      "Create 12 social media posts per month across 3 platforms",
      "Design on-brand graphics and carousel templates",
      "Write engaging captions with relevant hashtags",
      "Track engagement metrics and optimize content strategy",
    ],
    deliverables: [
      "12 designed posts per month with captions",
      "Content calendar for planning and approval",
      "Monthly engagement analytics report",
      "Brand-consistent template library",
    ],
    timeline: "Monthly retainer starting July 2026.",
    client: {
      name: "Alex Rivera",
      rating: 4.3,
      totalProjectsPosted: 2,
      memberSince: "May 2026",
      verified: false,
      avatar: "AR",
    },
    timelineSteps: [
      { label: "Project Posted", date: "Jun 11, 2026", status: "completed" },
      { label: "Applications Open", date: "Jun 11 – Jun 18", status: "current" },
      { label: "Selection", date: "Jun 19 – Jun 20", status: "upcoming" },
      { label: "Project Start", date: "Jun 22, 2026", status: "upcoming" },
    ],
  },
];

export function getProjectById(id: string): MarketplaceProject | undefined {
  return marketplaceProjects.find((p) => p.id === id);
}

export function getSimilarProjects(
  project: MarketplaceProject,
  limit = 4
): MarketplaceProject[] {
  return marketplaceProjects
    .filter((p) => p.id !== project.id)
    .sort((a, b) => {
      const aScore =
        (a.category === project.category ? 2 : 0) +
        a.skills.filter((s) => project.skills.includes(s)).length;
      const bScore =
        (b.category === project.category ? 2 : 0) +
        b.skills.filter((s) => project.skills.includes(s)).length;
      return bScore - aScore;
    })
    .slice(0, limit);
}
